import random


def guessTheNumber(x):
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("  Welcome to: Guess the Number!  ")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("Your goal is guess the random number generated by the computer. Good Luck!")

    numAl = random.randint(1,x) 

    prediction = 0

    while numAl != prediction:
        # The user enter a number
        prediction = int(input(f"Enter a number between 1 and {x}: "))

        if prediction < numAl:
            print("Try again, this number is less than the random number")
        elif prediction > numAl:
            print("Try again, this number is greater than the random number")
    
    print(f"Congratulations! You have guessed the number {numAl}")


guessTheNumber(10)
